// <auto-generated />
namespace FinalProgIII.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sincategoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sincategoria));
        
        string IMigrationMetadata.Id
        {
            get { return "201708092125148_sincategoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
